spring.application.name=Task-Manager-App

spring.data.mongodb.uri = mongodb+srv://ayanpakhira3018:i4QPbKdo3OsRdRip@cluster0.10n9bmd.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database = tododb
spring.data.mongodb.auto-index-creation = true
